Adds rattestation documentation
gyroidos/gyroidos.github.io pull request #40
Opened 2024-11-05 16:55 UTC by glad-dev

2024-11-05 16:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gyroidos/gyroidos.github.io?pullRequest=40) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gyroidos/gyroidos.github.io?pullRequest=40) before we can accept your contribution.<br/><hr/>**Gabriel Loyola Daiqui** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gyroidos/gyroidos.github.io?pullRequest=40) it.</sub>

2024-11-12 11:39 UTC, jwsbck requested changes

2024-11-12 11:39 UTC, jwsbck commented on _docs/operate/rattestation.md
> +## QMEU
QEMU

2024-11-12 11:39 UTC, jwsbck commented on _docs/operate/rattestation.md
> +The attestation tool cannot connect to the Container Management Layer (CML) when using a QEMU bride.
~~bride~~ bridge

2024-11-12 11:39 UTC, jwsbck commented on _docs/operate/rattestation.md
> +title: Remote attestation (rattestation)
i would remove the '(rattestation)' to not blow up the side bar menu.

2024-11-12 11:39 UTC, jwsbck commented on _docs/operate/rattestation.md
> +```bash
jekll seems not to support the ```bash syntax. It works for me without 'bash'. perhaps we can find another way, how we can have syntax highlighting.
![grafik](https://github.com/user-attachments/assets/195d8441-d9ad-4463-b6b0-dcd7548444c1)

2024-11-12 11:39 UTC, jwsbck commented on _docs/operate/rattestation.md
> +8. Run the attestation tool with `./rattestation 172.23.0.1`.
Perhaps we can have an example output of a successful attestation here at the end?

2024-11-12 15:38 UTC, glad-dev commented on _docs/operate/rattestation.md
> +## QMEU
Fixed in [5141b1d](https://github.com/gyroidos/gyroidos.github.io/pull/40/commits/5141b1d07bcc62fb6c5e0cc38a5bc9831a14aca8)

2024-11-12 15:38 UTC, glad-dev commented on _docs/operate/rattestation.md
> +The attestation tool cannot connect to the Container Management Layer (CML) when using a QEMU bride.
Fixed in [8044a49](https://github.com/gyroidos/gyroidos.github.io/pull/40/commits/8044a49356a27231ee50d15e8953d08043d188ff)

2024-11-12 15:39 UTC, glad-dev commented on _docs/operate/rattestation.md
> +title: Remote attestation (rattestation)
Fixed in [87b8b95](https://github.com/gyroidos/gyroidos.github.io/pull/40/commits/87b8b95eefd401b6fcecdea0770056ff37991fd7)

2024-11-12 15:44 UTC, glad-dev commented on _docs/operate/rattestation.md
> +```bash
I tried to use code-ray for syntax highlighting but it didn't work. For now I removed the `bash` keyword in [2d423f7](https://github.com/glad-dev/gyroidos.github.io/commit/2d423f78b994d7c2b59179809466aca3cd6c85dc)

2024-11-12 16:51 UTC, glad-dev commented on _docs/operate/rattestation.md
> +8. Run the attestation tool with `./rattestation 172.23.0.1`.
Added in [c79d42c](https://github.com/gyroidos/gyroidos.github.io/pull/40/commits/c79d42c040f0c700fbf11ee9a5d61a45f74f3f83)

2024-11-13 08:08 UTC, jwsbck approved these changes
very nice

2024-11-13 08:08 UTC, merged